### ISSUE TITLE
About X2.0 version

### ISSUE THREAD

**Issue by wy9884255** [miaow1988/ShuffleNet_V2_pytorch_caffe#16]
Thanks for sharing those models, would u mind provide the X2.0 version of ShufflenetV2, thank you

**Comment by miaow1988** [comment]
I have not trained a X2.0 model yet...

**Comment by wy9884255** [comment]
Thank you all the same!






At 2018-09-25 12:46:35, "Steven Miao" <notifications@github.com> wrote:


I have not trained a X2.0 model yet...
