### ISSUE TITLE
Training with the prototxt is slow

### ISSUE THREAD

**Issue by basaltzhang** [miaow1988/ShuffleNet_V2_pytorch_caffe#17]
In case of directly using the prototxt, please change the depthwise convolution layers type from **Convolution** into **DepthwiseConvolution**. After changing the 1.5x prototxt, the training speed up from ~14seconds/iter to 1s/iter.

**Comment by miaow1988** [comment]
Thanks for the comment.

**Comment by sweed111** [comment]
have you ever trained shufflenet with caffe? I have encored with a very strange problem when training. It will be very appreciate if you can get any comment or sugguestions.
My problem is this.

I trained shufflenet V2 0.5, with caffe windows, Cuda 10.1, Cudnn7.5，RTX2080.
I change the input size to 32*16 for my specific task. I also changed the prototxt files to make it work.
I do can train this net and get correct results like caffemodels and so on. My batch size is 16, My 8G gpu memory was used up to 7.3G.  I want to know what is the normal memory usage of a ordinary shuffenetv2 is, on any training platform. hope you can help, thanks

**Comment by miaow1988** [comment]
I haven't trained this model on Caffe. In Caffe, convolution with group is implemented by for loop with conventional convolution, which is a very expensive implementation.
In your case. I think you should replace group convolution with depthwise convolution.
