### ISSUE TITLE
About Top-1 Acc in ImageNet

### ISSUE THREAD

**Issue by hahanigehaha233** [miaow1988/ShuffleNet_V2_pytorch_caffe#26]
> shufflenet_v2_x0.50, Top-1 Acc = 58.93%. This accuracy is 1.37% lower compared with the result in the official paper.

but I saw [the paper](http://openaccess.thecvf.com/content_ECCV_2018/papers/Ningning_Light-weight_CNN_Architecture_ECCV_2018_paper.pdf), the x0.50 model only have 39.7% Top-1 Acc in Table 8.

**Comment by quziyan** [comment]
> > shufflenet_v2_x0.50, Top-1 Acc = 58.93%. This accuracy is 1.37% lower compared with the result in the official paper.
> 
> but I saw [the paper](http://openaccess.thecvf.com/content_ECCV_2018/papers/Ningning_Light-weight_CNN_Architecture_ECCV_2018_paper.pdf), the x0.50 model only have 39.7% Top-1 Acc in Table 8.

I have also got the same result, could you tell me how to solve it? THX
