### ISSUE TITLE
Could you please share the pretrained model?

### ISSUE THREAD

**Issue by JoeFannie** [miaow1988/ShuffleNet_V2_pytorch_caffe#3]
Hi,
    It is very nice of you sharing the code. Could you please also share the pretrained models?

**Comment by miaow1988** [comment]
Hi, I've shared my pretrained models here days ago. But I deleted the linked in the README.md accidentally. Now I've fixed the link.
Please download here.
https://github.com/miaow1988/ShuffleNet_V2_pytorch_caffe/releases

PS: Some models are still under training.
