### ISSUE TITLE
Convert pytorch to caffe Failed

### ISSUE THREAD

**Issue by MinZhaoLin** [miaow1988/ShuffleNet_V2_pytorch_caffe#30]
When I convert the pytorch model to the caffe model, I found that 0.25x model can be converted. But more than 0.25x model can not be converted. I found that the problem is that when I executed the conversion code, gpu0 memory is filled up quickly, leading to errors.

F1031 20:37:10.787436 16330 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
Aborted (core dumped)

I found that when the code is executed, there will be out of memory:
In def convert_to_caffe(self, name):  in slim.py
caffe_net = caffe.Net(name + '.prototxt', caffe.TEST)

**Comment by miaow1988** [comment]
Grouped convolution in Caffe is not optimized in both speed and memory. You'd better use CPU mode to convert your model.
If you still need to run this network in Caffe, you could add something like 'engine: "Caffe"' in the grouped convolution layers. Or replace grouped convolution layers with depthwise convolution layers.

**Comment by MinZhaoLin** [comment]
Thank you very much.
When I use the CPU mode by add "caffe.set_cpu_mode()", my gpu0 memory is still filled up quickly.
But adding "engine: CAFFE" in every convolution param in prototxt, it works. Thank you again for the answer.
