### ISSUE TITLE
Pytorch Pretrained Model Read Error 

### ISSUE THREAD

**Issue by jmnie** [miaow1988/ShuffleNet_V2_pytorch_caffe#4]
Hi, I downloaded the pretrained model in the release. 
I tried to read the model (shufflenet_v2_x0.5.pth), the code 

def test():  
    path = os.getcwd() + '/shufflenet_v2_x0.5.pth'
    model = torch.load(path)  
    torch.save(model.state_dict(), os.getcwd() + '/params.pth')  
    model_object.load_state_dict(torch.load(os.getcwd() + '/params.pth')) 

Error information here:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    test()
  File "test.py", line 9, in test
    torch.save(model.state_dict(), os.getcwd() + '/params.pth')  
AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'

the version of pytorch is 0.4.1. ( I am a newbee to pytorch and I am trying to convert the pytorch model to mxnet)

Could you kindly please provide the solution?

Thanks

**Comment by miaow1988** [comment]
Here are some codes snippets that may help you loading the pretrained model.
```
import shufflenet_v2
num_classes = 1000
model_width = 0.5
net = shufflenet_v2.Network(num_classes, model_width)
params = torch.load('shufflenet_v2_x0.5.pth', map_location=lambda storage, loc: storage)
net.load_state_dict(params)
```
